[tool.black]
line-length = 119

[tool.isort]
py_version = 38
line_length = 119
profile = "black"
known_third_party = ["creds", "gfpgan", "ray", "bridgeData"]

[tool.pylint.FORMAT]
max-line-length=500

[tool.ruff]
line-length = 500